### ISSUE TITLE
error al calificar copilotos

### ISSUE THREAD

**Issue by elriuk** [arNTC/unAventon#20]
cuando el conductor de un viaje califica a un copiloto solo, ademas se los califica a los demas

**Comment by cristiansteib** [comment]
@elriuk podrias detallar lo que sucede?

**Comment by elriuk** [comment]
Si señor!. 
este es el escenario:
conductor_1 con 3 pasajeros confirmados. copi_1, copi_2 y copi_3.
len(conductor_1.calificaionespendientesparacopilotos()= 3           hasta aca bien
entonces... 
conductor_1 califica solamente a copi_1
lo que ocurre...
len(conductor_1.calificaionespendientesparacopilotos())= 0      deberia ser 2

**Comment by cristiansteib** [comment]
@elriuk solucionado, el problema estaba en el filtro de la consulta.
